rewrite

diff --git a/scripts/sls-run b/scripts/sls-run
--- a/scripts/sls-run
+++ b/scripts/sls-run
@@ -1,31 +1,45 @@
 #!/bin/bash
 
-echo "ASSUMING ${PLUGIN_ROLE}"
-aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=drone > creds.json
+set -e
 
-export AWS_ACCESS_KEY_ID=`cat creds.json | jq -r '.Credentials.AccessKeyId'`
-export AWS_SECRET_ACCESS_KEY=`cat creds.json | jq -r '.Credentials.SecretAccessKey'`
-export AWS_SESSION_TOKEN=`cat creds.json | jq -r '.Credentials.SessionToken'`
+if [ -z $PLUGIN_ROLE ];
+then
+    echo "Error: please, aws role to assume"
+    exit 1
+fi
+
+echo "ASSUMING ${PLUGIN_ROLE}"
+CREDS=`aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}`
+
+export AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
+export AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
+export AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`
 
 USER=`aws sts get-caller-identity |  jq -r '.Arn'`
-
 echo "ASSUMED $USER"
 
-npm install
 
-if [ "$PLUGIN_ACTION" = "test" ] 
+if [ "$PLUGIN_CREATE_DOMAIN" = "true" ] 
 then
-    echo "RUNNING TESTS"
-
-    npm run test
+    echo "CREATE DOMAIN"
+    node_modules/.bin/sls create_domain -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION} -v
 fi
 
 if [ "$PLUGIN_ACTION" = "deploy" ] 
 then
+    ARGS=""
     
-    echo "CREATE DOMAIN"
-    node_modules/.bin/sls create_domain -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION}
-    
+    if [ "$PLUGIN_CONCEAL" = "true" ] 
+    then
+        ARGS="$ARGS --conceal"
+    fi
+
+    if [ "$PLUGIN_ACCELERATE" = "true" ] 
+    then
+        ARGS="$ARGS --aws-s3-accelerate"
+    fi
+
     echo "DEPLOY"
-    node_modules/.bin/sls deploy  -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION}
+    node_modules/.bin/sls deploy ${ARGS} -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION} -v
 fi
+
